variables:
  SEMANTIC_RELEASE_EXTRA_ARGS: --repository-url https://github.com/claranet/terraform-claranet-default-tags
  SHARED_RUNNER_TAG: ops4ops-claranet

include:
  - project: claranet/guildes/pipeline/terraform-templates/terraform-gitlab-ci-templates
    ref: v0.29.3
    file: terraform_module.yml
